### ISSUE TITLE
title overflow when long string

### ISSUE THREAD

**Issue by AErmek** [fluttercandies/extended_sliver#11]
Hi, thanks for package.
Could you please help me to fix my issue?
So when I set very long title text inside title widget, I'm getting overflow exception.

```
ExtendedSliverAppbar(
      mainAxisAlignment: MainAxisAlignment.start,
      title: Text(
              "Very long long long long long long title",
              overflow: TextOverflow.ellipsis,
              maxLines: 1,
              softWrap: false,
              textAlign: TextAlign.start,
            ),
...)
```

I also tried to use Row with flexible, but didn't help:

```
ExtendedSliverAppbar(
      mainAxisAlignment: MainAxisAlignment.start,
      title: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Flexible(
            child: Text(
              "Very long long long long long long title",
              overflow: TextOverflow.ellipsis,
              maxLines: 1,
              softWrap: false,
            ),
          ),
        ],
      ),
```

What should I do, to give ellipsis behavior in Title?

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_sliver/blob/0c67fac9edc16b09a88b9e1f9d17bc09d8504d49/lib/src/widget.dart#L374

**Comment by AbdulazizRasulbek** [comment]
When isOpacityFadeWithTitle: true title is wrapped with Opacity so wrapping title to Expand widget is not working. 
Only option is wrapping sizedbox and giving static size to title
