### ISSUE TITLE
[InAppWebViewExample] updateAcquireFence: Did not find frame.

### ISSUE THREAD

**Issue by iDevOrz** [fluttercandies/extended_sliver#15]
Getting ``updateAcquireFence: Did not find frame`` in debugging log
```E/FrameEvents(31705): updateAcquireFence: Did not find frame.
E/FrameEvents(31705): updateAcquireFence: Did not find frame.
E/FrameEvents(31705): updateAcquireFence: Did not find frame.
E/FrameEvents(31705): updateAcquireFence: Did not find frame.
```

[✓] Flutter (Channel stable, 3.0.5, on macOS 12.5 21G72 darwin-arm, locale en-CN)
    • Flutter version 3.0.5 at /Users/devorz/fvm/versions/3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (5 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

**Comment by zmtzawqlp** [comment]
runnable, simple demo
