### ISSUE TITLE
ExtendedSliverAppbar centerTitle

### ISSUE THREAD

**Issue by mustofa-al** [fluttercandies/extended_sliver#2]
Seem like the title always center, is that so?
Could yo please provide an option to align the title, and hide the back button in the next release? Thanks

**Comment by zmtzawqlp** [comment]
ExtendedSliverAppbar(leading:Contianer(),mainAxisAlignment : MainAxisAlignment.start)

https://github.com/fluttercandies/extended_sliver/commit/51c850aa058cf4fff4385a04b877e3a73a8bdb9f

**Comment by mustofa-al** [comment]
Thanks
