### ISSUE TITLE
ExtendedSliverAppbar的background属性里面有Hero组件的时候会报错

### ISSUE THREAD

**Issue by shun007** [fluttercandies/extended_sliver#6]
提示有两个一样的tag

**Comment by zmtzawqlp** [comment]
可以看源码，自己改一下。计算background 高度的widget别带hero

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/extended_sliver/blob/cdd0e09892ddc8f1167ae6d4813a4727b4b7a3f2/lib/src/widget.dart#L217
