### ISSUE TITLE
ExtendedSliverAppbar title文本超过屏幕时越界

### ISSUE THREAD

**Issue by iptodays** [fluttercandies/extended_sliver#7]
![image](https://user-images.githubusercontent.com/15830996/126966046-56a78f7b-199c-4477-bc9d-22988524b47e.png)

**Comment by khaledMahmoudDev** [comment]
wrap your text with SizedBox and and add width to the sizedBox 
for me 
                          SizedBox(
                            width: MediaQuery.of(context).size.width *.8,
                            child:
                            Text( longText,  ),
                          ),

**Comment by zmtzawqlp** [comment]
@iptodays you can try as @khaledMahmoudDev  said.

**Comment by austinried** [comment]
Using MediaQuery here is not a good solution here I think, how do I know for sure that my actions take up the other 20% of the space in this example?

Why doesn't the parent widget for title provide a width constraint?
